# Generated by Django 4.0.6 on 2022-07-16 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('todo', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
