# Generated by Django 4.0.6 on 2022-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('todo', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
